"""empty message

Revision ID: 22fa982ad1db
Revises: 
Create Date: 2019-03-07 11:45:53.130820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22fa982ad1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.add_column('user', sa.Column('acceptedTerms', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['istid'])
    op.drop_column('user', 'remember_token')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('remember_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'acceptedTerms')
    op.create_table('contact',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remember_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('istid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=u'contact_pkey')
    )
    # ### end Alembic commands ###
